"""initial schema

Revision ID: ba8e9613d44b
Revises: 
Create Date: 2026-08-25 21:44:43.011613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba8e9613d44b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synth_truth',
    sa.Column('truth_uid', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pattern_type', sa.Text(), nullable=False),
    sa.Column('cell_id', sa.BigInteger(), nullable=False),
    sa.Column('ts_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ts_end', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('kpi_affected', sa.Text(), nullable=False),
    sa.Column('magnitude', sa.Double(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('truth_uid'),
    schema='analytics'
    )
    op.create_table('dim_technology',
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.Column('technology', sa.Text(), nullable=False),
    sa.Column('release', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('technology_id'),
    sa.UniqueConstraint('technology'),
    schema='dims'
    )
    op.create_table('dim_vendor',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('vendor_id'),
    sa.UniqueConstraint('vendor_name'),
    schema='dims'
    )
    op.create_table('cm_changes',
    sa.Column('change_uid', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cell_id', sa.BigInteger(), nullable=False),
    sa.Column('parameter', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('changed_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('change_uid'),
    schema='raw'
    )
    op.create_table('fm_alarms',
    sa.Column('alarm_uid', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raised_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('cleared_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('enb_id', sa.BigInteger(), nullable=False),
    sa.Column('cell_id', sa.BigInteger(), nullable=True),
    sa.Column('alarm_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('source_system', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('alarm_uid'),
    schema='raw'
    )
    op.create_table('pm_measurements',
    sa.Column('ts', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('enb_id', sa.BigInteger(), nullable=False),
    sa.Column('cell_id', sa.BigInteger(), nullable=False),
    sa.Column('counter_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Double(), nullable=True),
    sa.Column('gran_period_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ts', 'cell_id', 'counter_id'),
    schema='raw'
    )
    op.create_table('dim_counter',
    sa.Column('counter_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kpi_group', sa.Text(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('vendor_counter_name', sa.Text(), nullable=True),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['technology_id'], ['dims.dim_technology.technology_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['dims.dim_vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('counter_id'),
    sa.UniqueConstraint('name'),
    schema='dims'
    )
    op.create_table('dim_enb',
    sa.Column('enb_id', sa.BigInteger(), nullable=False),
    sa.Column('enb_name', sa.Text(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['dims.dim_vendor.vendor_id'], ),
    sa.PrimaryKeyConstraint('enb_id'),
    sa.UniqueConstraint('enb_name'),
    schema='dims'
    )
    op.create_table('dim_cell',
    sa.Column('cell_id', sa.BigInteger(), nullable=False),
    sa.Column('cell_name', sa.Text(), nullable=False),
    sa.Column('enb_id', sa.BigInteger(), nullable=False),
    sa.Column('sector', sa.Integer(), nullable=True),
    sa.Column('earfcn', sa.Integer(), nullable=True),
    sa.Column('archetype', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('azimuth_deg', sa.Double(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enb_id'], ['dims.dim_enb.enb_id'], ),
    sa.PrimaryKeyConstraint('cell_id'),
    sa.UniqueConstraint('cell_name'),
    schema='dims'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dim_cell', schema='dims')
    op.drop_table('dim_enb', schema='dims')
    op.drop_table('dim_counter', schema='dims')
    op.drop_table('pm_measurements', schema='raw')
    op.drop_table('fm_alarms', schema='raw')
    op.drop_table('cm_changes', schema='raw')
    op.drop_table('dim_vendor', schema='dims')
    op.drop_table('dim_technology', schema='dims')
    op.drop_table('synth_truth', schema='analytics')
    # ### end Alembic commands ###
