apiVersion: 1

datasources:
  - name: telcoscope-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: telcoscope
    user: telcoscope
    secureJsonData:
      password: telcoscope
    jsonData:
      sslmode: "disable"
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
